import { useState } from 'react'

import { createGitHubPR, type BackendConfig } from '@/lib/orchestra-client'

export function useIssueDetailPR({
  config,
  identifier,
  title,
  description,
}: {
  config: BackendConfig | null
  identifier: string
  title: string
  description: string
}) {
  const [prPending, setPrPending] = useState(false)
  const [prResult, setPrResult] = useState<{ url: string; number: number } | null>(null)
  const [prDialogOpen, setPrDialogOpen] = useState(false)
  const [prTitle, setPrTitle] = useState('')
  const [prBody, setPrBody] = useState('')
  const [prHead, setPrHead] = useState('')

  const handleCreatePR = () => {
    setPrTitle(title || `feat(${identifier}): solution implementation`)
    setPrBody(description || `Resolves ${identifier}\n\nThis PR was autonomously generated by Orchestra after a successful task execution.`)
    setPrHead(`task/${identifier}`)
    setPrDialogOpen(true)
  }

  const handleFinalizePR = async () => {
    if (!config || !identifier) return
    setPrPending(true)
    try {
      const response = await createGitHubPR(config, identifier, {
        title: prTitle,
        body: prBody,
        head: prHead,
        base: 'main',
      })
      setPrResult(response)
      setPrDialogOpen(false)
    } catch (err) {
      console.error('Failed to create PR:', err)
      alert('Failed to create PR: ' + (err instanceof Error ? err.message : String(err)))
    } finally {
      setPrPending(false)
    }
  }

  return {
    prPending,
    prResult,
    prDialogOpen,
    setPrDialogOpen,
    prTitle,
    setPrTitle,
    prBody,
    setPrBody,
    prHead,
    handleCreatePR,
    handleFinalizePR,
  }
}
